name: Build slides
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🏗️" build french assets
      - run: bash build.sh -l fr
      - run: echo "🏗️" build english assets
      - run: bash build.sh -l en