name: Build slides
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🌀 Build Start"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "🏗️" build french assets
      - run: bash build.sh -l fr
      - run: echo "🏗️" build english assets
      - run: bash build.sh -l en